### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Merith-TK** [G1itchZero/zeronet-go#4]
as the title asks, is this project dead?

**Comment by Merith-TK** [comment]
```
 ⇛ http server started on :43111
> 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D
Download site: 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x762ad2]

goroutine 38 [running]:
panic(0x7f7b60, 0xc042004090)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/G1itchZero/zeronet-go/peer_manager.(*PeerManager).announceHTTP(0xc0422f81e0, 0x8780a7, 0x25, 0x7, 0x1, 0x0)
        C:/Users/averr_000/Documents/go/src/github.com/G1itchZero/zeronet-go/peer_manager/peer_manager.go:180 +0x472
github.com/G1itchZero/zeronet-go/peer_manager.(*PeerManager).announceTracker(0xc0422f81e0, 0x8780a7, 0x25, 0x0, 0x0, 0x0)
        C:/Users/averr_000/Documents/go/src/github.com/G1itchZero/zeronet-go/peer_manager/peer_manager.go:324 +0x177
github.com/G1itchZero/zeronet-go/peer_manager.(*PeerManager).Announce.func1(0xc0422f81e0, 0x8780a7, 0x25)
        C:/Users/averr_000/Documents/go/src/github.com/G1itchZero/zeronet-go/peer_manager/peer_manager.go:94 +0x61
created by github.com/G1itchZero/zeronet-go/peer_manager.(*PeerManager).Announce
        C:/Users/averr_000/Documents/go/src/github.com/G1itchZero/zeronet-go/peer_manager/peer_manager.go:114 +0xda```
